quarkus.http.port=8080

# ---- REST clients hacia "Salesforce" (nuestro mock en dev) ----
quarkus.rest-client.salesforce-api.url=${SF_BASE_URL:http://localhost:8081}
quarkus.rest-client.salesforce-api.connect-timeout=3000
quarkus.rest-client.salesforce-api.read-timeout=10000

quarkus.rest-client.salesforce-auth.url=${SF_LOGIN_URL:http://localhost:8081}
quarkus.rest-client.salesforce-auth.connect-timeout=3000
quarkus.rest-client.salesforce-auth.read-timeout=10000

# ---- Config propia del adaptador Salesforce ----
app.salesforce.api-version=v60.0
app.salesforce.auth.client-id=3MVG9-CONSUMER-KEY-FAKE
app.salesforce.auth.username=integracion@banco.ec
app.salesforce.auth.audience=http://localhost:8081
app.salesforce.token-ttl-minutes=20

# ---- Firma del JWT assertion ----
smallrye.jwt.sign.key.location=classpath:privateKey.pem
smallrye.jwt.new-token.signature-algorithm=RS256

# ---- Logging del client en dev (nunca en prod con datos reales) ----
%dev.quarkus.rest-client.logging.scope=request-response
%dev.quarkus.rest-client.logging.body-limit=1024
%dev.quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
