version: "3.9"

services:
  sf-mock:
    build:
      context: sf-mock
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8081"
    environment:
      - QUARKUS_HTTP_PORT=8081

  cuentas-service:
    build:
      context: cuentas-service
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
      - SF_BASE_URL=http://sf-mock:8081
      - SF_LOGIN_URL=http://sf-mock:8081
    depends_on:
      - sf-mock
